config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/about', to: 'meals#about'
  get '/download', to: 'meals#download'
  get '/contact', to: 'meals#contact'
  get '/categories', to: 'meal_details#category'
  get '/meal_details', to: 'meal_details#details'
  get '/category_meals', to: 'meal_details#list'


  root to: 'static#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meal_details_controller.rb
class MealDetailsController < ApplicationController
  def category
    client = Meal::Api::Client.new
    @category_list = client.category_list
    @category_list.each do |category|
      @categoryList = category[1]
    end
  end 
  
  def details
    client = Meal::Api::Client.new
    @meal_details= client.meal_details(params[:id])
    @meal_details.each do |mealDetails|
      @youtube_link = mealDetails[1][0]["strYoutube"]
    end
    @youtube = YouTubeAddy.extract_video_id(@youtube_link)
  end

  def list
    client = Meal::Api::Client.new
    @category_details= client.meal_category(params[:category])
    @category_details.each do |catDetails|
      @categoryDetails = catDetails[1]
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def about
  end

  def download
  end

  def contact
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
    client = Meal::Api::Client.new
    @randoms = client.random_meals
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="header" > 
      <div class="logo"> Foodle </div>
      <div class="navigation">
        <div><%= link_to 'Home', root_path %></div>
        <div><%= link_to 'About', about_path %></div>
        <div><%= link_to 'Recipes', categories_path %></div>
        <div><%= link_to 'Download', download_path %></div>
        <div><%= link_to 'Contact', contact_path %></div>
      </div>
      <div class="back"><%= link_to "Back", :back %></div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/meal_details/category.html.erb
<div class="list_category">
  <% @categoryList.each do |category| %>
    <div class="category_card">
      <div class="category_card_details">
        <%= link_to category["strCategory"], category_meals_path(:category => category["strCategory"]), :class => "category_card_title" %>
        <div class="category_card_desc"><%= category["strCategoryDescription"]%></div>
      </div> 
      <div><%= image_tag category["strCategoryThumb"], :class => "category_card_image"%></div>
    </div>
  <% end %>
</div>

app/views/meal_details/details.html.erb
<div class="individual_meal">
  <% @meal_details.each do |details| %>
  <div class="meal_details">
    <div class="meal_details_text">
      <div class="meal_details_name"><%= details[1][0]["strMeal"] %></div>
      <div class="meal_details_category"><%= details[1][0]["strCategory"] %></div>
      <div class="meal_more_details"><%= details[1][0]["strInstructions"] %></div>
    </div>
    <div class="meal_details_image"><%= image_tag details[1][0]["strMealThumb"]+"/preview", :class => "meal_details_image_spec" %></div>
  </div>
  <div class="meal_other_details">
    <div class="ing_table">
      <div class="ing_title">Ingredients</div>
      <div class="ing_names">
        <ul class="ing_name"><%= details[1][0]["strMeasure1"]+ " " + details[1][0]["strIngredient1"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure2"]+ " " + details[1][0]["strIngredient2"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure3"]+ " " + details[1][0]["strIngredient3"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure4"]+ " " + details[1][0]["strIngredient4"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure5"]+ " " + details[1][0]["strIngredient5"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure6"]+ " " + details[1][0]["strIngredient6"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure7"]+ " " + details[1][0]["strIngredient7"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure8"]+ " " + details[1][0]["strIngredient8"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure9"]+ " " + details[1][0]["strIngredient9"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure10"]+ " " + details[1][0]["strIngredient10"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure11"]+ " " + details[1][0]["strIngredient11"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure12"]+ " " + details[1][0]["strIngredient12"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure13"]+ " " + details[1][0]["strIngredient13"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure14"]+ " " + details[1][0]["strIngredient14"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure15"]+ " " + details[1][0]["strIngredient15"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure16"]+ " " + details[1][0]["strIngredient16"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure17"]+ " " + details[1][0]["strIngredient17"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure18"]+ " " + details[1][0]["strIngredient18"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure19"]+ " " + details[1][0]["strIngredient19"] %></ul>
        <ul class="ing_name"><%= details[1][0]["strMeasure20"]+ " " + details[1][0]["strIngredient20"] %></ul>
      </div>
    </div>
    <div class="ing_vid">
      <iframe width="500px" height="300px" src='https://www.youtube.com/embed/<%=@youtube%>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe>
    </div>
  </div>
  <% end %>
</div>

app/views/meal_details/index.html.erb
<div>
  <% @categoryList.each do |category| %>
    <div>
      <%= category["strCategory"] %>
      <%= category["strCategoryDescription"] %>
      <%= image_tag category["strCategoryThumb"]%>
    </div>
  <% end %>
</div>

app/views/meal_details/list.html.erb
<div class="food_category_list">
  <% @categoryDetails.each do |cateDetails| %>
    <div class="food_category">
      <div class="food_category_name"><%= link_to cateDetails["strMeal"], meal_details_path(:id => cateDetails["idMeal"]) %></div>
      <%= link_to image_tag(cateDetails["strMealThumb"], :class => "category_card_image"), meal_details_path(:id => cateDetails["idMeal"])%>
    </div>
  <% end %>
</div>

app/views/meals/download.html.erb
<div class="body">
  <div class="food_reference"><%= image_tag 'app-ref.png' %></div>
  <div class="section_one">
    <h1 class="section_header"> Get the App </h1>
    <div class="section_body"> Our app is available on the App Store and Play Store, you can download for free for a more comfortable experience</div>
  <div class="food-ref-store"><%= image_tag 'app-store.png' %></div>
  </div>
</div>